let player1 = document.getElementById('player1')
let player2 = document.getElementById('player2')
let s1=document.getElementById('score-p1')
let s2=document.getElementById('score-p2')
let btn_Go=document.getElementById('go')
let btn_PlayAgain=document.getElementById('playAgain')
let boxes = Array.from(document.getElementsByClassName('box'))
let scorePlayer1 = 0;
let scorePlayer2 = 0;
let arr=Array(9).fill("")
const O="O"
const X="X"
let currentPlayer=X
let winner=''
playerT=document.getElementById('playerText')